[package]
name = "js_bridge_macro"
version = "0.1.0"
authors = ["Surma <surma@surma.link>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.19", features = ["full"] }
quote = "1.0.4"
proc-macro2 = "1.0.12"
